baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Portfolio'

[markup.goldmark.renderer]
  unsafe = true

[params]
  # This kills the lightbox magnification script globally
  enableLightbox = false
